# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:

    # CUSTOM
    ide: 'phpstorm://open?url=file://%%f&line=%%l'
    property_access:
        magic_call: true
    # END CUSTOM

    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 36000 # 10 heures
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    # pour inclure directement des methodes de controller comme vue embarquée
    fragments: { path: /_fragment }

#when@prod:
#    framework:
#        http_cache: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
