framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'no-reply@lalune.net'
            # Bcc
            # recipients: ['nicolas@capside.fr']
        headers:
            From: '%env(SITE)% <no-reply@lalune.net>'
            To: '%env(CLIENT_EMAIL)%'
