twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        site: '%app.site%'
        upload_path: '%app.upload_path%'
        fo: '%app.fo%'
        fo_path: '%app.fo_path%/'
        recaptcha_site_key: '%app.recaptcha_site_key%'

    date:
        format: 'F j, Y H:i'
        timezone: 'Europe/Paris'


when@test:
    twig:
        strict_variables: true
