# TEST VICHUPLOAD BUNDLE
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        cms_media:
            uri_prefix: /assets/dyn-upload
            upload_destination: '%kernel.project_dir%/public/assets/dyn-upload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above
#            namer: Vich\UploaderBundle\Naming\SlugNamer
