controllers:
    resource: ../src/Controller/
    type: annotation
    prefix:
        fr: ''
        en: '/en'
        nl: '/nl'
        de: '/de'
        es: '/es'

kernel:
    resource: ../src/Kernel.php
    type: annotation
